### ISSUE TITLE
data volume

### ISSUE THREAD

**Issue by flavioaraki** [mariadb-corporation/mariadb-columnstore-docker#1]
As I'm evaluating ColumnStore (on Docker for Mac), I often find myself having to rebuild the containers in order to try different setups. Thus, having the data inside the container is inconvenient since I have to reload the database as well.

I mounted `/usr/local/mariadb/columnstore/data` and `/usr/local/mariadb/columnstore/data1` as volumes, but attempting to create a table will throw `ERROR 1815 (HY000): Internal error: CAL0009: Error while calling getSysCatDBRoot`.

Is there a way to persist the data on container rebuilds? If yes, please update the documentation. Thank you.

**Comment by davidwbt** [comment]
Hi, are you using the docker setup that is published by us:
https://github.com/mariadb-corporation/mariadb-columnstore-docker or your
own?

If you are using ours can you provide the docker build logs and also
columnstore logs? If you have developed your own check ours as a reference
as this should work.

David.

**Comment by lucianjon** [comment]
We ended up adding this block to our install.sh script, it allows you to mount out the directories without having the permissions stamped over.

```
MCS_HOME=/usr/local/mariadb/columnstore
DEFAULT_DATA_DIR=/raid/var/lib/mcs-default
MCS_DATA_DIR=/raid/var/lib/mcs

# put the actual original files in a separate directory
mkdir -p $DEFAULT_DATA_DIR
mkdir -p $DEFAULT_DATA_DIR/mysql
mv $MCS_HOME/data1 $DEFAULT_DATA_DIR/data1
mv $MCS_HOME/mysql/db $DEFAULT_DATA_DIR/mysql/db

# symlink the original files into the real directory
# this directory is the one that gets mapped to when starting docker
# this means that if we start this image without a volume mapping it'll still run
mkdir -p $MCS_DATA_DIR
mkdir -p $MCS_DATA_DIR/mysql
ln -s $DEFAULT_DATA_DIR/data1 $MCS_DATA_DIR/data1
ln -s $DEFAULT_DATA_DIR/mysql/db $MCS_DATA_DIR/mysql/db

# point the infinidb directories at the files in the directory that would be volume mapped
ln -s $MCS_DATA_DIR/data1 $MCS_HOME/data1
ln -s $MCS_DATA_DIR/mysql/db $MCS_HOME/mysql/db

# when we start up docker we check if MCS_DATA_DIR contains each of the files in DEFAULT_DATA_DIR
# it then copies over any missing files (using `cp -rp` to preserve permissions - mysql requires mysql:mysql on its files)
# this provides a way to automatically set up the volume mapped directory for new hosts```

**Comment by Nithos** [comment]
Is there anything else that is needed?
Changing/keeping permission for /mysql/db does not seem to work, so not sure what else I am missing.
