### ISSUE TITLE
Error in post-install: "unary operator expected"

### ISSUE THREAD

**Issue by gnagel** [mariadb-corporation/mariadb-columnstore-docker#2]
I'm getting a warning from the RPM package installer when building the docker image: "/usr/local/mariadb/columnstore/bin/post-install: line 12: [: !=: unary operator expected"

The build still finishes successfully, but it would be nice to remove this warning.

Thanks!

[build.txt](https://github.com/mariadb-corporation/mariadb-columnstore-docker/files/692111/build.txt)

**Comment by davidwbt** [comment]
This is a bug in the rpm install scripts,hopefully we'll get that fixed in the next release.

**Comment by gnagel** [comment]
Thanks David 👍
