### ISSUE TITLE
docker image is too big

### ISSUE THREAD

**Issue by weilin705** [mariadb-corporation/mariadb-columnstore-docker#4]
The mcs is too big，1.3G.
This is normal ?
I am currently using version is 1.0.9

**Comment by weilin705** [comment]
@davidwbt

**Comment by davidwbt** [comment]
This is normal unfortunately. MariaDB server and it's dependencies consume a reasonable chunk of this. The original goal of this was to enable people to try out columnstore on a pc or a mac so function was the priority. Some basic docker things are done to reduce the size of the image but it likely could be a bit leaner maybe with a different base distro than centos7.  MariaDB server takes up a fair amount of the size plus ColumnStore depends on some core linux functions so you can't run on a very lean distro.

**Comment by weilin705** [comment]
I have another question, when I remove the image, I create database has been deleted, how do I configure this
@davidwbt

**Comment by davidwbt** [comment]
The default image uses docker volumes for the file locations where data is persisted. Standard docker commands e.g. docker volume can be used to view and remove volumes as appropriate.
