### ISSUE TITLE
Mounting external drive

### ISSUE THREAD

**Issue by Nithos** [mariadb-corporation/mariadb-columnstore-docker#7]
Is there a way to mount an external drive to be used for storage?
It seems as soon as I mount /data1 it will fail on create table calls (Error while calling getSysCatDBRoot ). Seems there is a permissions issue or implied settings that can not be changed.

Details:
Using docker-compose

cs-db:
    image: columnstore-singlenode:latest
    ports:
      - "3306:3306"
    restart: always
    **volumes:
      - ./volumes/data1:/usr/local/mariadb/columnstore/data1**

Any help is appreciated.
Thank You

**Comment by davidwbt** [comment]
I haven't seen this problem before but when i've created compose file i've generally followed the pattern of having named volumes and then referencing them in the specific container section.   Also can you elaborate on what you mean specifically by mount /data1 - are you doing something specific in the container? As long as the volume is writable and by root it should be fine

**Comment by Nithos** [comment]
Thank for the information.

Seems that using 'named volumes' in the compose or externally works. However doing a regular -v (-mount) fails due to some permissions problems with mysql. This is a limitation as this means that Docker manages the volume so an externally accessible volume is not possible at this time (at least not by simply doing the -v mount)
